# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IHStMIekHMD-DYI_2UTq59LZ-eAD07Sy
"""

import streamlit as st
import torch
import numpy as np
from PIL import Image
from model import LogisticRegression
import torchvision.transforms as transforms
from streamlit_drawable_canvas import st_canvas

# ---------------- Page Config ----------------
st.set_page_config(
    page_title="Digit Recognition App",
    page_icon="✍️",
    layout="wide"
)

# ---------------- Load Model ----------------
input_size = 28 * 28
num_classes = 10

model = LogisticRegression(input_size, num_classes)
model.load_state_dict(torch.load("digit_model.pth", map_location="cpu"))
model.eval()

# ---------------- Sidebar ----------------
st.sidebar.title("✍️ Digit Recognition")
st.sidebar.markdown(
    """
    **Tech Stack**
    - PyTorch
    - Streamlit
    - Logistic Regression

    **Features**
    - Draw a digit
    - Upload an image
    - Real-time prediction
    """
)

mode = st.sidebar.radio("Choose Input Method", ["Draw Digit", "Upload Image"])

# ---------------- Main UI ----------------
st.markdown(
    "<h1 style='text-align:center;'>Handwritten Digit Recognition</h1>",
    unsafe_allow_html=True
)

st.markdown(
    "<p style='text-align:center;'>AI model that predicts handwritten digits (0–9)</p>",
    unsafe_allow_html=True
)

st.divider()

# ---------------- Preprocessing ----------------
transform = transforms.Compose([
    transforms.Resize((28, 28)),
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,))
])

# ---------------- Draw Digit ----------------
if mode == "Draw Digit":
    col1, col2 = st.columns([1, 1])

    with col1:
        st.subheader("✏️ Draw Here")
        canvas = st_canvas(
            fill_color="black",
            stroke_width=12,
            stroke_color="white",
            background_color="black",
            height=280,
            width=280,
            drawing_mode="freedraw",
            key="canvas"
        )

    with col2:
        st.subheader("🔍 Prediction")

        if canvas.image_data is not None:
            img = canvas.image_data[:, :, 0]
            img = Image.fromarray(img).convert("L")

            img_tensor = transform(img)
            img_tensor = img_tensor.view(1, -1)

            with torch.no_grad():
                outputs = model(img_tensor)
                probs = torch.softmax(outputs, dim=1)
                pred = torch.argmax(probs, dim=1).item()
                confidence = probs[0][pred].item() * 100

            st.success(f"**Predicted Digit:** {pred}")
            st.info(f"**Confidence:** {confidence:.2f}%")

# ---------------- Upload Image ----------------
if mode == "Upload Image":
    col1, col2 = st.columns([1, 1])

    with col1:
        st.subheader("📤 Upload Image")
        uploaded_file = st.file_uploader(
            "Upload a digit image (PNG/JPG)",
            type=["png", "jpg", "jpeg"]
        )

    with col2:
        st.subheader("🔍 Prediction")

        if uploaded_file:
            image = Image.open(uploaded_file).convert("L")
            st.image(image, width=200)

            img_tensor = transform(image)
            img_tensor = img_tensor.view(1, -1)

            with torch.no_grad():
                outputs = model(img_tensor)
                probs = torch.softmax(outputs, dim=1)
                pred = torch.argmax(probs, dim=1).item()
                confidence = probs[0][pred].item() * 100

            st.success(f"**Predicted Digit:** {pred}")
            st.info(f"**Confidence:** {confidence:.2f}%")

# ---------------- Footer ----------------
st.divider()
st.markdown(
    "<p style='text-align:center;'>Built with ❤️by shubham using PyTorch & Streamlit</p>",
    unsafe_allow_html=True
)